#filter emptyLines

#define MOZ_LANG_TITLE zh-CN

#define MOZ_LANGPACK_CREATOR Firefox Chinese Forums

#define MOZ_LANGPACK_HOMEPAGE http://www.firefox.net.cn/

# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
#define MOZ_LANGPACK_CONTRIBUTORS <em:contributor>Fang5566</em:contributor> <em:contributor>Fiag</em:contributor> <em:contributor>kingkong</em:contributor> <em:contributor>Smoke</em:contributor> <em:contributor>desatan</em:contributor> <em:contributor>dangerboy_dx</em:contributor> <em:contributor>ccbbs</em:contributor> <em:contributor>Moses</em:contributor> 

#unfilter emptyLines
