#!/bin/bash
# Should make $AB_CD $L10NDIR right.

XPI=$(realpath ../chatzilla/mozilla/extensions/irc/xpi)

export AB_CD=zh-CN
export L10NDIR=$XPI/../locales/$AB_CD

TOOLKIT=$L10NDIR/../../toolkit
if [ ! -d $TOOLKIT ]
then
	mkdir $TOOLKIT
fi
touch $L10NDIR/../../toolkit/defines.inc

cd $XPI
bash makelocalexpi.sh
